---
- hosts: AWS_EC2_app
  gather_facts: yes
  become: true

  tasks:

    - name: Install Nginx
      become: yes
      apt:
        name: nginx
        state: present

    - name: Disable default
      become: yes
      command:
        cmd: unlink /etc/nginx/sites-enabled/default
      ignore_errors: yes

    - name: Create nginx.conf
      become: yes
      file:
        path: /etc/nginx/sites-available/rev_proxy.conf
        state: touch

    - name: Write nginx.conf
      become: yes
      blockinfile:
        path: /etc/nginx/sites-available/rev_proxy.conf
        marker: ""
        block: |
          server {
              listen 80;
              location / {
                  proxy_pass http://127.0.0.1:3000;
                  proxy_set_header Authorization "";
                  proxy_read_timeout 90s;
              }
          }

    - name: Link nginx.conf
      become: yes
      command:
        cmd: ln -s /etc/nginx/sites-available/rev_proxy.conf /etc/nginx/sites-enabled/rev_proxy.conf

    - name: Ensure service is running
      become: yes
      service:
        name: nginx
        state: restarted
        enabled: yes
